# RetailPulse - Data Loading & Cleaning

## Objective
The objective of this notebook is to:
- Load the Online Retail II dataset.
- Understand the dataset structure.
- Identify missing values and duplicates.
- Clean the dataset.
- Save the cleaned dataset for further analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = "../Data/raw/online_retail_II.xlsx"

df = pd.read_excel(file_path)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
df.shape

(525461, 8)

In [4]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 38.8+ MB

In [6]:
df.describe()

            Quantity                 InvoiceDate          Price    Customer ID
count  525461.000000                      525461  525461.000000  417534.000000
mean       10.337667  2010-06-28 11:37:36.845018       4.688834   15360.645478
min     -9600.000000         2009-12-01 07:45:00  -53594.360000   12346.000000
25%         1.000000         2010-03-21 12:20:00       1.250000   13983.000000
50%         3.000000         2010-07-06 09:51:00       2.100000   15311.000000
75%        10.000000         2010-10-15 12:45:00       4.210000   16799.000000
max     19152.000000         2010-12-09 20:01:00   25111.090000   18287.000000
std       107.424110                         NaN     146.126914    1680.811316

In [7]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(6865)

In [9]:
# Create a copy of the original dataset
clean_df = df.copy()

In [10]:
# Remove duplicate records
clean_df = clean_df.drop_duplicates()

print("Duplicate rows removed successfully.")
print("Remaining rows:", clean_df.shape[0])

Duplicate rows removed successfully.
Remaining rows: 518596

In [11]:
clean_df.duplicated().sum()

np.int64(0)

In [12]:
clean_df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [13]:
clean_df.nunique()

Invoice        28816
StockCode       4632
Description     4681
Quantity         825
InvoiceDate    25296
Price           1606
Customer ID     4383
Country           40
dtype: int64

In [14]:
# Convert InvoiceDate to datetime
clean_df["InvoiceDate"] = pd.to_datetime(clean_df["InvoiceDate"])

# Verify datatype
clean_df["InvoiceDate"].dtype

dtype('<M8[us]')

In [15]:
# Count cancelled invoices
clean_df[clean_df["Invoice"].astype(str).str.startswith("C")].shape

(10182, 8)

In [16]:
# Remove cancelled invoices
clean_df = clean_df[~clean_df["Invoice"].astype(str).str.startswith("C")]

print("Cancelled invoices removed.")
print("Remaining rows:", clean_df.shape)

Cancelled invoices removed.
Remaining rows: (508414, 8)

In [17]:
# Check records with negative quantity
clean_df[clean_df["Quantity"] <= 0].shape

(2121, 8)

In [18]:
# Keep only positive quantities
clean_df = clean_df[clean_df["Quantity"] > 0]

print("Negative quantities removed.")
print(clean_df.shape)

Negative quantities removed.
(506293, 8)

In [19]:
# Check invalid prices
clean_df[clean_df["Price"] <= 0].shape

(1563, 8)

In [20]:
# Keep only positive prices
clean_df = clean_df[clean_df["Price"] > 0]

print("Invalid prices removed.")
print(clean_df.shape)

Invalid prices removed.
(504730, 8)

In [21]:
# Remove rows where Customer ID is missing
clean_df = clean_df.dropna(subset=["Customer ID"])

print("Missing Customer ID removed.")
print(clean_df.shape)

Missing Customer ID removed.
(400916, 8)

In [22]:
clean_df["Description"].isnull().sum()

np.int64(0)

In [23]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 400916 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  object
 1   StockCode    400916 non-null  object
 2   Description  400916 non-null  object
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[us]
 5   Price        400916 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      400916 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.7+ MB

In [24]:
clean_df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [25]:
clean_df.to_csv("../Data/processed/clean_online_retail.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [26]:
clean_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [27]:
clean_df.shape

(400916, 8)

In [28]:
clean_df.to_csv("Retail_Cleaned.csv", index=False)

# Conclusion

### Data Cleaning Summary

- Loaded the Online Retail II dataset.
- Explored the dataset structure.
- Removed duplicate records.
- Removed cancelled invoices.
- Removed records with invalid quantity and price.
- Removed missing Customer ID and Description.
- Saved the cleaned dataset for further analysis.

The dataset is now ready for Exploratory Data Analysis (EDA) and Machine Learning.